CREATE TABLE TB_STATUS_MOTO (
                                id_status NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                descricao_status VARCHAR2(50 CHAR) NOT NULL
);
-- Tabela de Usuários
CREATE TABLE TB_USUARIO (
                            id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            nome_usuario VARCHAR2(100 CHAR) NOT NULL,
                            email_usuario VARCHAR2(100 CHAR) NOT NULL UNIQUE,
                            senha_usuario VARCHAR2(100 CHAR) NOT NULL,
                            role VARCHAR2(20 CHAR) DEFAULT 'USER' NOT NULL,
                            CONSTRAINT chk_usuario_role CHECK (role IN ('USER', 'ADMIN'))
);

-- Tabela de Pátios
CREATE TABLE TB_PATIO (
                          id_patio NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          id_usuario NUMBER NOT NULL,
                          cep_patio VARCHAR2(9 CHAR),
                          numero_patio VARCHAR2(10 CHAR),
                          cidade_patio VARCHAR2(50 CHAR),
                          estado_patio VARCHAR2(2 CHAR),
                          capacidade_patio NUMBER(10) NOT NULL,
                          CONSTRAINT chk_patio_capacidade CHECK (capacidade_patio > 0),
                          CONSTRAINT chk_patio_estado CHECK (LENGTH(estado_patio) = 2)
);

-- Tabela de Motocicletas
CREATE TABLE TB_MOTO (
                         id_moto NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         id_status NUMBER NOT NULL,
                         id_patio NUMBER NOT NULL,
                         placa_moto VARCHAR2(10 CHAR) NOT NULL UNIQUE,
                         chassi_moto VARCHAR2(20 CHAR) NOT NULL UNIQUE,
                         nr_motor_moto VARCHAR2(50 CHAR) NOT NULL UNIQUE,
                         modelo_moto VARCHAR2(50 CHAR) NOT NULL
);

-- Tabela de Antenas
CREATE TABLE TB_ANTENA (
                           id_antena NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           id_patio NUMBER NOT NULL,
                           codigo_antena VARCHAR2(50 CHAR) NOT NULL UNIQUE,
                           latitude_antena NUMBER(10, 6) NOT NULL,
                           longitude_antena NUMBER(10, 6) NOT NULL,
                           CONSTRAINT chk_antena_latitude CHECK (latitude_antena BETWEEN -90 AND 90),
                           CONSTRAINT chk_antena_longitude CHECK (longitude_antena BETWEEN -180 AND 180)
);

-- Tabela de Tags RFID/WiFi
CREATE TABLE TB_TAG (
                        id_tag NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        codigo_rfid_tag VARCHAR2(50 CHAR) NOT NULL UNIQUE,
                        ssid_wifi_tag VARCHAR2(50 CHAR) NOT NULL,
                        latitude_tag NUMBER(10, 6) NOT NULL,
                        longitude_tag NUMBER(10, 6) NOT NULL,
                        data_hora_tag TIMESTAMP NOT NULL,
                        CONSTRAINT chk_tag_latitude CHECK (latitude_tag BETWEEN -90 AND 90),
                        CONSTRAINT chk_tag_longitude CHECK (longitude_tag BETWEEN -180 AND 180)
);

-- Tabela de Relacionamento Moto-Tag (N:N)
CREATE TABLE TB_MOTO_TAG (
                             id_moto NUMBER NOT NULL,
                             id_tag NUMBER NOT NULL,
                             data_associacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                             PRIMARY KEY (id_moto, id_tag)
);
