CREATE TABLE TB_STATUS_MOTO (
                                id_status NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                descricao_status VARCHAR2(50 CHAR) NOT NULL
);

CREATE TABLE TB_USUARIO (
                            id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            nome_usuario VARCHAR2(100 CHAR) NOT NULL,
                            email_usuario VARCHAR2(100 CHAR) NOT NULL UNIQUE,
                            senha_usuario VARCHAR2(100 CHAR) NOT NULL,
                            role VARCHAR2(20 CHAR) NOT NULL DEFAULT 'USER'
);

CREATE TABLE TB_PATIO (
                          id_patio NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          id_usuario INTEGER NOT NULL,
                          cep_patio VARCHAR2(9 CHAR),
                          numero_patio VARCHAR2(10 CHAR),
                          cidade_patio VARCHAR2(50 CHAR),
                          estado_patio VARCHAR2(2 CHAR),
                          capacidade_patio INTEGER
);

CREATE TABLE TB_MOTO (
                         id_moto NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         id_status INTEGER NOT NULL,
                         id_patio INTEGER NOT NULL,
                         placa_moto VARCHAR2(10 CHAR) UNIQUE,
                         chassi_moto VARCHAR2(20 CHAR) UNIQUE,
                         nr_motor_moto VARCHAR2(50 CHAR) UNIQUE,
                         modelo_moto VARCHAR2(50 CHAR) NOT NULL
);

CREATE TABLE TB_ANTENA (
                           id_antena NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           id_patio INTEGER NOT NULL,
                           codigo_antena VARCHAR2(50 CHAR) NOT NULL,
                           latitude_antena NUMBER(10, 6) NOT NULL,
                           longitude_antena NUMBER(10, 6) NOT NULL
);

CREATE TABLE TB_TAG (
                        id_tag NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        codigo_rfid_tag VARCHAR2(50 CHAR) NOT NULL,
                        ssid_wifi_tag VARCHAR2(50 CHAR) NOT NULL,
                        latitude_tag NUMBER(10, 6) NOT NULL,
                        longitude_tag NUMBER(10, 6) NOT NULL,
                        data_hora_tag TIMESTAMP NOT NULL
);

CREATE TABLE TB_MOTO_TAG (
                             id_moto INTEGER NOT NULL,
                             id_tag INTEGER NOT NULL,
                             PRIMARY KEY (id_moto, id_tag)
);